### ISSUE TITLE
能来个文档吗

### ISSUE THREAD

**Issue by IgnorantFool** [longbeidou/taobaokev3#1]

**Comment by longbeidou** [comment]
获取淘宝客对应的商品信息请参照淘宝客的composer包（https://github.com/longbeidou/taobaoke），通过这个包可以方便的获取商品信息。

**Comment by longbeidou** [comment]
获取淘宝客对应的商品信息请参照淘宝客的composer包（https://github.com/longbeidou/taobaoke ) 通过这个包可以方便的获取商品信息。
