### ISSUE TITLE
想提一个关于模板方面的建议..

### ISSUE THREAD

**Issue by HelplessMan** [longbeidou/taobaokev3#14]
说实话项目看着很不错。而且后续的需求感觉也是我特别想要滴。就是。反正怎么都是套模板。麻烦第四版本的话。 模板可不可以弄一个炒鸡好看滴。。。

**Comment by longbeidou** [comment]
这个可以有，计划搞个多端多套的发布版本，敬请期待

**Comment by HelplessMan** [comment]
好的好的~  下个版本大约啥时候可以好呢。。还是比较着急的。。哈哈哈，有木有列个计划表呢。。
